name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish -c Release -o published
        
      - name: Prepare Static Web App
        run: |
          # Copy staticwebapp.config.json to the root of published/wwwroot
          cp staticwebapp.config.json published/wwwroot/
          cp web.config published/wwwroot/
          
          # Ensure CSS and JS directories exist
          mkdir -p published/wwwroot/css
          mkdir -p published/wwwroot/js
          
          # Copy static assets
          cp -r wwwroot/css/* published/wwwroot/css/ || true
          cp -r wwwroot/js/* published/wwwroot/js/ || true
          
          # Copy favicon and other assets
          cp wwwroot/favicon.png published/wwwroot/ || true
          cp wwwroot/index.html published/wwwroot/
          cp wwwroot/appsettings.json published/wwwroot/
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_FACEIT_MAX_STATS }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "published/wwwroot"
          api_location: "api"
          output_location: ""
          skip_app_build: true
          
        env:
          FACEIT_API_KEY: ${{ secrets.FACEIT_API_KEY }}
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_FACEIT_MAX_STATS }}
          action: "close"